In [10]:
#===========TASK1 FIBONACCI =======
def my_fibonaci(x):
    fib=[1, 1]         # Значеннч 1-го та 2-го елементу Фібоначчі
    if x<3:
        rezult=1
    else:        
        for i in range(2,x):
            fib.append(fib[i-2]+fib[i-1])   # Значеннч n-го елементу Фібоначі
        rezult=fib[i]
    return rezult

print(" ==== TASk1 - FIBONACCI ELEMENTS ====")
print(f'The value of 60th element of Fiboncci numbers is: [{my_fibonaci(60)}]')


 ==== TASk1 - FIBONACCI ELEMENTS ====
The value of 60th element of Fiboncci numbers is: [1548008755920]


In [11]:
#===========TASK2 Lin Algebra =======
print(" ==== TASK2 - SOLVING THE SYSTEM OF 3 LINEAR EQUATIONS WITH 3 VARIABLES ====")
import numpy as np
A_matr=np.array([[1, 2, 3], [0, 1, 2], [2, 0, 0]])
print(f'\nThe A Matrix is: \n {A_matr}')
B_matr=np.array([1, 1, 0])
print(f'\nThe B Matrix is: \n {B_matr}')
#--Розв’язок рівнянь
answers = np.linalg.solve(A_matr, B_matr)

print(f"\nSolution is X={answers}")

 ==== TASK2 - SOLVING THE SYSTEM OF 3 LINEAR EQUATIONS WITH 3 VARIABLES ====

The A Matrix is: 
 [[1 2 3]
 [0 1 2]
 [2 0 0]]

The B Matrix is: 
 [1 1 0]

Solution is X=[ 0. -1.  1.]


In [ ]:
#===========TASK3 Lin Algebra =======
print(" ==== TASK3 -  ====")

In [9]:
#===========TASK3 Lin Algebra =======
print(" ==== TASK4 -  ====")

 ==== TASK4 -  ====
